import Head from 'next/head'
import Link from 'next/link'
import{FaGithubSquare, FaLinkedin} from 'react-icons/fa'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>DevDré</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className='bg-gray-800 px-10'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
          <Image src="/logo1.png" alt="" width="200" height="30"/>
            <ul className='flex items-center'>
              <li>
                <a className='bg-red-500 text-white px-4 py-2 rounded-md ml-8 ' href='#'>Download CV</a>
              </li>
            </ul>
          </nav>
          <div className='text-center p-10 py-10'>
          <h2 className='text-5xl py-2 text-red-400 font-extralight'>Andre Felipe</h2>
          <h3 className='text-5xl py-2 text-white'>Desenvolvedor beckend</h3>
          <p className='text-md py-5 leading-8 text-white'>
            sguDDGBghdsjoouisdguyhsdvhSJhui
          </p>
          </div>
          <div className='text-5xl flex justify-center gap-0.5'>
            <FaGithubSquare/>
            <FaLinkedin />
          </div>
          <div>
            <Image src="/eu.png" alt="" width="400" height="400" className='relative mx-auto bg-gradient-to-b from-red-400 rounded-full'/>
          </div>
        </section>
      </main>
    </div>
  )
}
